### PR TITLE
reponsive menu

### PR DESCRIPTION
**Pull request by guilhermeorcezi**
i did the responsive menu works and the responsive content too

### CODE REVIEW

**Comment by guilhermeorcezi** [comment]
Sorry, I thought that this way would have no problem. Already fixed, see if this is correct.

**Comment by noob-master147** [comment]
@guilhermeorcezi you have conflicts with the PR
Please open a new PR against `Navbar` branch and pull that branch before making a PR.

Thank you so much :)

**Comment by guilhermeorcezi** [comment]
I think now is correct? I mean, Im new to git so these branch specs got a little confusing, sorry for the inconvenience.

**Comment by noob-master147** [comment]
@guilhermeorcezi I've gone through your code and tested it. Everything is working as expected.
GREAT WORK
The only issue is the conflict that are arising because you might have forgot to pull the master before the PR. I'm closing this PR for now but I look forward to you for a new PR.
Do this :
pull the repository once for the updated codes you might have missed
open a new PR against the `Navbar` branch: THIS IS REALLY IMPORTANT

**Comment by guilhermeorcezi** [comment]
I'm sorry, I can't understand what it means to open a new PR against the Navbar branch

**Comment by noob-master147** [comment]
@guilhermeorcezi  don't worry ill walk you through this.

when you're about to create a new PR
image

You will get an option to choose the branch like this:
image

so select the `navbar` and create a PR

**Comment by guilhermeorcezi** [comment]
Thank you! I think i did right now...

**Pull request closed without merging**
